package view;

import com.lowagie.text.*;
import com.lowagie.text.pdf.*;

import javax.swing.*;
import java.awt.event.*;
import java.io.FileOutputStream;
import java.sql.*;
import java.time.LocalDate;

public class FormStatistik extends JFrame {
    private JLabel lblStat;
    private JButton btnExport;
    private int totalKunjungan;

    public FormStatistik() {
        setTitle("Statistik Kunjungan");
        setSize(400, 300);
        setLayout(null);
        setLocationRelativeTo(null);

        lblStat = new JLabel();
        lblStat.setBounds(80, 100, 300, 30);
        add(lblStat);

        btnExport = new JButton("Export PDF");
        btnExport.setBounds(120, 160, 140, 30);
        add(btnExport);

        btnExport.addActionListener(e -> exportToPDF());

        ambilTotalKunjungan();
        setVisible(true);
    }

    private void ambilTotalKunjungan() {
        try {
            Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/klinik", "root", ""); // sesuaikan user/pass
            PreparedStatement ps = conn.prepareStatement(
                "SELECT COUNT(*) FROM statistik_kunjungan " +
                "WHERE MONTH(tanggal_kunjungan) = ? AND YEAR(tanggal_kunjungan) = ?"
            );

            LocalDate today = LocalDate.now();
            ps.setInt(1, today.getMonthValue());
            ps.setInt(2, today.getYear());

            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                totalKunjungan = rs.getInt(1);
                lblStat.setText("Total Kunjungan Bulan Ini: " + totalKunjungan);
            }

            rs.close();
            ps.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal mengambil data dari database.");
        }
    }

    private void exportToPDF() {
        try {
            Document document = new Document();
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Simpan PDF Statistik");
            fileChooser.setSelectedFile(new java.io.File("statistik_kunjungan.pdf"));

            int userSelection = fileChooser.showSaveDialog(this);
            if (userSelection != JFileChooser.APPROVE_OPTION) return;

            PdfWriter.getInstance(document, new FileOutputStream(fileChooser.getSelectedFile()));
            document.open();

            Font titleFont = new Font(Font.HELVETICA, 18, Font.BOLD);
            Paragraph title = new Paragraph("Statistik Kunjungan Bulanan", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            document.add(new Paragraph(" "));
            document.add(new Paragraph("Total Kunjungan Bulan Ini: " + totalKunjungan));
            document.add(new Paragraph("Tanggal: " + LocalDate.now()));
            document.add(new Paragraph(" "));
            document.add(new Paragraph("Generated by Aplikasi Klinik", new Font(Font.HELVETICA, 10)));

            document.close();
            JOptionPane.showMessageDialog(this, "PDF berhasil disimpan!");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuat PDF: " + ex.getMessage());
        }
    }

    public static void main(String[] args) {
        // Pastikan driver MySQL sudah tersedia
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); // pakai mysql-connector-java 8.x
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "MySQL Driver tidak ditemukan!");
            return;
        }

        SwingUtilities.invokeLater(FormStatistik::new);
    }
}
