package view;

import com.lowagie.text.*;
import com.lowagie.text.pdf.*;

import javax.swing.*;
import java.io.FileOutputStream;
import java.sql.*;
import java.time.LocalDate;

import config.koneksi;

public class FormStatistik extends JFrame {
    private JLabel lblStat;
    private JButton btnExport;
    private int totalKunjungan;

    public FormStatistik() {
        setTitle("Statistik Kunjungan");
        setSize(400, 300);
        setLayout(null);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        lblStat = new JLabel("Memuat data...");
        lblStat.setBounds(80, 100, 300, 30);
        add(lblStat);

        btnExport = new JButton("Export PDF");
        btnExport.setBounds(120, 160, 140, 30);
        btnExport.setEnabled(false);
        add(btnExport);

        btnExport.addActionListener(e -> exportToPDF());

        ambilTotalKunjungan();
        setVisible(true);
    }

    private void ambilTotalKunjungan() {
        try (Connection conn = koneksi.getKoneksi()) {
            String sql = "SELECT COUNT(*) FROM statistik_kunjungan WHERE MONTH(tanggal_kunjungan) = ? AND YEAR(tanggal_kunjungan) = ?";
            try (PreparedStatement ps = conn.prepareStatement(sql)) {
                LocalDate today = LocalDate.now();
                ps.setInt(1, today.getMonthValue());
                ps.setInt(2, today.getYear());

                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        totalKunjungan = rs.getInt(1);
                        lblStat.setText("Total Kunjungan Bulan Ini: " + totalKunjungan);
                        btnExport.setEnabled(true);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal mengambil data dari database.");
        }
    }

    private void exportToPDF() {
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.setDialogTitle("Simpan PDF Statistik");
            chooser.setSelectedFile(new java.io.File("statistik_kunjungan.pdf"));

            if (chooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) return;

            Document doc = new Document();
            PdfWriter.getInstance(doc, new FileOutputStream(chooser.getSelectedFile()));
            doc.open();

            Font titleFont = new Font(Font.HELVETICA, 18, Font.BOLD);
            Paragraph title = new Paragraph("Statistik Kunjungan Bulanan", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            doc.add(title);
            doc.add(Chunk.NEWLINE);

            doc.add(new Paragraph("Tanggal: " + LocalDate.now()));
            doc.add(new Paragraph("Total Kunjungan Bulan Ini: " + totalKunjungan));
            doc.add(Chunk.NEWLINE);
            doc.add(new Paragraph("Generated by Aplikasi Klinik", new Font(Font.HELVETICA, 10, Font.ITALIC)));

            doc.close();
            JOptionPane.showMessageDialog(this, "PDF berhasil disimpan!");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal membuat PDF.");
        }
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(FormStatistik::new);
    }
}
